### ISSUE TITLE
attribute error

### ISSUE THREAD

**Issue by 5l1v3r1** [AzizKpln/walterRat#6]
Traceback (most recent call last):
  File "walterRat.py", line 1425, in <module>
    wRat=walterRat()
  File "walterRat.py", line 18, in __init__
    print colors["BOLD"]
TypeError: 'module' object has no attribute '__getitem__'

**Comment by AzizKpln** [comment]
which version of python are you using

**Comment by 5l1v3r1** [comment]
python 2.7 kali 2020. most probably the problem is about ansicolors module. __getitem__ should be called before defining another module like wRat=walterRat(). I tried to fix it but no chance :/

**Comment by AzizKpln** [comment]
Does the program keep giving the same error? Did you try to run it again? i May have made a mistake on that line

**Comment by 5l1v3r1** [comment]
yes it gives the same error everytime, i think you can disable the color effect of the script which seems unneccessary or you can use another module instead.
i think those modules conflict:
https://pypi.org/project/ansicolors/ (from __future__ import print_function  # accomodate Python 2
from colors import *)
https://pythonhosted.org/pycolors/ (from colors import Color)

you can use colorama,termcolor or colored modules instead.

**Comment by AzizKpln** [comment]
I Will not be on pc for 2-3 days but after that I Will check the tool if I encounter an error ill fix it thanks for reporting the error
